### ISSUE TITLE
Bad name...

### ISSUE THREAD

**Issue by CodeAndWeb** [andydbc/unity-texture-packer#1]
Hi,

would you mind renaming it back to ChannelPacker? TexturePacker might really be confusing for the users:

https://www.codeandweb.com/texturepacker
https://assetstore.unity.com/packages/tools/sprite-management/texturepacker-importer-16641

Thanks.

Best
Andreas

**Comment by andydbc** [comment]
Hi Andreas,

I don't mind changing it to ChannelPacker, sorry for the inconvenience.

Andy

**Comment by CodeAndWeb** [comment]
Great, thanks.
