### ISSUE TITLE
Excuse my ignorance

### ISSUE THREAD

**Issue by suhdude1738** [andydbc/unity-texture-packer#4]
How on earth do i install this? Ive tried a couple of things but i cannot seem to get it working.

**Comment by andydbc** [comment]
Hello, 
I've turned this into a package, you can follow the instructions under:

https://github.com/andydbc/unity-texture-packer/tree/master#install

let me know if you have questions, 
Andy

**Comment by Tommy-Wilkinson** [comment]
For the installation instructions adding the line to the manifest.json kept giving me an error. Unity said it was not correct JSON. However, simply unzipping and adding through the package manager worked and automatically added the dependency to the manifest.json. I'm not sure if the first step is necessary at all.
