### ISSUE TITLE
Baking to alpha channel doesn't work

### ISSUE THREAD

**Issue by Neonagee** [andydbc/unity-texture-packer#5]
Alpha channel doesn't shows up in the texture preview and generated texture has no alpha.

**Comment by andydbc** [comment]
Alpha is working, you just need to enable it in the Texture import settings
![Unity_2019-12-15_23-27-02](https://user-images.githubusercontent.com/31256170/70879224-8ed17780-1f92-11ea-9091-12d4f4fa130f.png)

**Comment by Neonagee** [comment]
It works only when Input texture has alpha. Baking RGB channels to alpha doesn't work

**Comment by andydbc** [comment]
Tested all cases and It worked in all cases
